### ISSUE TITLE
Twin clients die when connection is lost

### ISSUE THREAD

**Issue by jafcobend** [cosmos72/twin#78] opened 2022-09-28 17:46 UTC
As mentioned I'm now using TWIN in place of `screen` and `tmux`. The main reason I used those was to prevent apps from being killed if my SSH connection broke. I seem to have stumbled into an odd case where the apps in my TWIN session get killed if that connection is lost.

Basic steps to reproduce:

1. From a terminal session (xterm or similar) start `twin --hw=tty`
2. Enable the socket server
3. "File | Execute" some apps: twsysmon, twterm, twxmms2, ...
4. Now close your terminal session (not TWIN), to simulate a loss of connection.
5. `twattach` your session
6. See that everything launched from "File | Execute" died.

I'm _guessing_ that something (SIGHUP?) is signalling through the the server when launched with the TTY driver. Apps built-in to the server survive, ie the automatic initial `twterm`. Once the connection between the TWIN server and the TTY is severed things behave as you expect. You can `twattach` your session launch whatever and _lose_ your connection and everything stays put and running as expected.

A slightly similar situation:

1. From a terminal in TWIN  do `twterm &`
2. Go back to the initial terminal and close it. Whatever TWIN app (twsysmon, ...) you launched from that terminal dies.

In X I frequently launch apps from a terminal and they survive the closing of the terminal. But definitely the more odd thing is that first situation. One would think that all things launched from within TWIN would be safe from extermination should the TWIN "display" go away.

I have verified this on several systems and in both ARM32 and AMD64 architectures.

**Comment by Mirppc** [comment] 2022-09-28 17:54
I will test this later.. i dont use Screen but i do use Byobu which uses Tmux on the backend.

**Comment by cosmos72** [comment] 2022-09-28 18:05
Issue confirmed.

I checked, and `xterm` installs a SIGHUP handler, and continues running after receiving a SIGHUP due to its standard input tty going away (i.e. going back to the initial terminal used to launch `xterm`, and close that).
I checked another X program `xfontsel` and it quits instead in the same situation.

I guess the takeaway is: if a program does not use the tty it is launched from, for example because it opens a new window (X11, libtw...) and its only interface is through that new window, then it should intercept (or block?) SIGHUP.

That's something I can easily add to `twterm`, `twsysmon` etc.

**Comment by jafcobend** [comment] 2022-09-28 18:30
I suppose what confuses me and seems broken is the signal getting **through** the server to the apps. Bear in mind my usual scenario where I first ran into this:

1. SSH into a remote machine.
2. Launch `twin --hw=tty`
3. Launch twin apps/clients
4. Lose SSH connection.
5. Go back to recover... all external apps \*gone\*. **oops**

How did SIGHUP (or whatever signaling) get from my connection, through the TWIN display and the server to kill the apps? That path should be broken.

If I use the "File | Detach" menu item everything works as expected. Everything is still there and operating after I re-`twattach` it. 

If I start TWIN with `--nohw` or otherwise detach from the server (close window, kill connection, ...) then re-`twattach` it everything works as expected and clients survive further accidental detaches.

And that will likely be my temporary fix: a script to `twin --nohw` + ` twattach ...`. To break that signal path.

But yes, I agree that the TWIN apps/clients should ignore SIGHUP after they connect to the TWIN server. Perhaps libTw should do that automatically?

**Comment by cosmos72** [comment] 2022-09-28 19:04
Hmm... I am missing a small but important detail:
> 3. Launch twin apps/clients
means you start them from Fille|Execute,
from a twin builtin terminal,
or from a `twterm` client?

Some of these mechanisms detach themselves from the controlling tty, others don't.

And IIRC File|Execute does **not** detach the forked program from twin's controlling tty - which is likely a bug, as it probably should

**Comment by jafcobend** [comment] 2022-09-28 19:15
Well... I thought it was a bug. ;-) But yes, if I launch clients using "File | Execute" or launch from a `twterm` client they die. If I launch with the built in terminal they live. It would seem like that the server and all its children should be detached from the original launching TTY. They should survive until the server is signaled to close ("File | Quit").

**Comment by cosmos72** [comment] 2022-09-29 18:00
Commit 9cfb8ef04e89738d5f5c2ee71b13bce8e298093d starts fixing this issue: `twterm` and `twsysmon` now survive their controlling tty being closed.

I'm still working on the other cases.

**Comment by cosmos72** [comment] 2022-09-29 18:55
Commit f92a0067ec07c78dee3368e63ed722759ff30a13 fixes File|Execute to start new processes without controlling tty and with file descriptors 0, 1 and 2 connected to `/dev/null`

**Comment by jafcobend** [comment] 2022-09-29 19:16
Great work. I'll check this out as soon as I can. Thanks!

**Comment by jafcobend** [comment] 2022-10-01 03:54
I finally got to backport my patches on to the new source and I've tested it on amd64 and `twterm`, `twsysmon`, `twxmms2` survived an SSH connection to my test machine getting dropped. All of the other architectures are busy baking. I'll know more about them tomorrow. Thanks again!

**Comment by cosmos72** [comment] 2022-10-01 10:10
Good :)
Do you think your patches are relevant enough to be merged into master branch?
Doing that would surely make your life easier :)

**Comment by jafcobend** [comment] 2022-10-01 15:52
Well.... look at issue #74 and you tell me. ;-)

**Comment by jafcobend** [comment] 2022-10-01 17:42
I can report that the new code builds on all my target platforms and processes launched in TWIN survive sudden disconnects. At least "twterm" and "twssymon" processes. I don't have many other choices at the moment. :-)

**Comment by cosmos72** [comment] 2022-10-01 18:27
Good :)

**Closed by cosmos72** 2022-10-01 18:27 UTC
Labels: enhancement
