### ISSUE TITLE
Input is _dead_ in `twterm` on 32-bit systems

### ISSUE THREAD

**Issue by jafcobend** [cosmos72/twin#75] opened 2022-09-19 21:39 UTC
This is kind of a place holder bug. I wanted to get it out while I was thinking about it. If I launch TWIN on an ARM32 platform (tested deb7-9) and in the default "twterm" window type something like `twterm &` the new window ignores all input, including clicking the close button. I have to go back to the originating twterm `fg...` it and ^C it to get it to go away. If I use either the TWIN default menu or the twterm menu to launch another instance all is well. I think this also affects other apps like `twcat`.

I need to do more testing. And I need to review the build logs for problems. I built my current packages on the lowest common version of Debian on ARM Deb7. I'll try building on Deb 9.

This surprised me because I routinely do this on amd64 and RISC-V 64 hardware without problems. Most of the amd64 hardware is also Deb7 and I have used it on Deb 8 and 11. The binaries were compiled on Deb5. The RISC-V machine is using a testing version of Ubuntu, Jammie I think it was. Which will likely be Deb12, when it gets released.

**Comment by cosmos72** [comment] 2022-09-21 12:48
Hi @jafcobend,

from the symptoms you describe, it seems either libtw is broken on ARM32, or the server-side implementation of libtw in socket.cpp is broken on ARM32.

Could you post what happens if you run `strace twlsobj` instead of `twterm` ?

**Comment by jafcobend** [comment] 2022-09-21 15:29
There is another symptom that I believe is related and makes me think the issue is in the server. On the ARM32 long running TWIN processes seem to hang. How I noticed this was my LEDs stopped blinking!

Let me explain: as mentioned in the configuration discussion I started using TWIN to host long running processes and capture their screen output. The vast majority of the time TWIN is running _headless_. One of those processes checks various /proc files for system status and updates a bank of LEDs via a homemade device on an I2C bus. This is run on a Raspberry Pi 2B. It ran for a day or so and then the LEDs stopped blinking. When I tried to `twattach` the session it claimed there wasn't a TWIN server at that address (`--twin@:0`). `ps` confirmed the processes (TWIN, LEDs, ...) were still there. I had to kill the TWIN server process and restart it.

NOTE: I've been running this process on this device for over a year. Its been running in an xterm hosted by VNC. I was hoping to dump the bloat. :-D

I need to do more testing on this hang issue too. It will be a few days to try things. And I'll have to fire up long running TWIN servers on other devices.

The output from the programs that I was hosting in the TWIN session is relatively minor. One of the processes basically just marks time, waiting for something to do, spitting out a 30ish char line once a minute or so. It doesn't normally have much to do and this run it did nothing else. The other program  that runs the LEDs is more active spitting out cursor move commands and updating about a dozen chars on the _screen_ every 1/10th second. I'm sure it all accumulates to a significant volume.

I will run your test **AND** test the twterm on i386 (32b). I'm pretty sure I've done that and it worked. But I'll perform this specific test and post the results here. The `twterm` hang is quick to test. ;-) The long running issue... needs time to "run long". :-D And hopefully I can come up with things for them to do and remember to check on them. Hmm... I can actually run the exact same programs on all my device types. I'll do that for the most accurate test.

I figure I'll have to `gdb` it next time to see if there is something I can make anything out of. Since I'm not familiar with the server architecture that ought to be interesting! And I'll have to recompile with debug info. I'll narrow down which architectures have troubles first!

**Comment by jafcobend** [comment] 2022-09-21 16:07
@cosmos72 I confirmed that the input dies on both ARM32 and i386 (32b) when launching twterm from another twterm. here is the output you requested:

[strace.txt](https://github.com/cosmos72/twin/files/9618408/strace.txt)
[twlsobj.txt](https://github.com/cosmos72/twin/files/9618410/twlsobj.txt)

I also tried closing the `twterm &` window with "window | close" and that didn't work either. Then I used `fg` in the launching `twterm` but the child `twterm` failed to respond. ^C to the rescue!

**Comment by cosmos72** [comment] 2022-09-21 16:11
I see. So it's really an issue on 32-bit builds.

Strange that `twlsobj` did not trigger it. Would you mind to `strace twterm` too and post the result?
I am trying to figure out where the bug is...

**Comment by jafcobend** [comment] 2022-09-21 17:05
@cosmos72 if this helps I just tried something else: `twterm -e watch ... &`. My intent was to see if the `twterm` process was hung in the `D` state. The result was that `twterm` was not. It was in the normal `S` state. And `watch` kept updating the display. Time changed every 2sec per the default and the command output was updated. That's a pretty frequent _recipe_ I use.

In short it appears that the server isn't sending back data (keys, clicks, ...) for some reason. That doesn't make much sense to me since the server would be unaware of the fact that the client was launched _background_. So maybe the client is simply going deaf on data coming back from the server. `twlsobj > twlsob.out &` works so its obviously reading back from the socket. `twcat &` seems to also work. I don't know what keystrokes its supposed to respond to. But I can scroll the window with the various mouse operations (wheel, scroll buttons, drag thumb, ...).

And, lastly, for the grins-and-gigles of it I changed `TWDISPLAY=localhost:1` and retried the `twterm ... &` test. It also fails. So it doesn't matter whether its a UNIX or TCP socket. I also verified with `netstat` that there was a TCP connection between `twterm` and TWIN.

**Comment by cosmos72** [comment] 2022-09-21 18:49
I was expecting `strace twterm` to show that twterm was not receiving keypress events,
instead it's receiving at least *some* events:
```
select(5, [3 4], NULL, NULL, NULL)      = 1 (in [3])
ioctl(3, FIONREAD, [13])                = 0
read(3, "\t\0\0\0Msg!\0\20\0\0\21", 13) = 13
select(5, [3 4], NULL, NULL, NULL)      = 1 (in [3])
ioctl(3, FIONREAD, [13])                = 0
read(3, "\t\0\0\0Msg!\0\20\0\0\21", 13) = 13
```
judging from the bytes `\0\20\0\0\21` these seem "open another terminal" events though - which are then completely ignored for some reason.

**Comment by jafcobend** [comment] 2022-09-21 19:51
@cosmos72 I reran the strace and this time poked a bunch of random keys.  Don't forget I have to ^C the process to get out of the unresponsive `twterm`. The end of the strace is likely to be missing stuff. Here's the new run with key presses:

[strace.txt](https://github.com/cosmos72/twin/files/9619922/strace.txt)

Since I normally launch `twterm` from `twterm` using `&` I thought I should try it foreground. The new `twterm` still did not respond. Here's the `strace` of that including key presses:

[strace2.txt](https://github.com/cosmos72/twin/files/9619932/strace2.txt)

**Comment by cosmos72** [comment] 2022-09-22 06:58
As you correctly point out, starting `twterm` or `twterm &` does not make difference - and twin is completely  unaware whether it was started in foreground or background.

Both your new `strace.txt` and `strace2.txt` show the same problem described above: keypress events received by `twterm` are malformed, and get ignored:
```
select(5, [3 4], NULL, NULL, NULL)      = 1 (in [3])
ioctl(3, FIONREAD, [13])                = 0
read(3, "\t\0\0\0Msg!\0\20\0\0\21", 13) = 13
select(5, [3 4], NULL, NULL, NULL)      = 1 (in [3])
```
This is a good starting point for me to debug the server, thanks

**Comment by cosmos72** [comment] 2022-09-23 21:08
I cleaned up some buggy code in commit 036fb3f790e17ced879b173f9de00c4027ca1235 - can you test if it fixes the issue?

My arm64 box (an OdroidC2 with an arm32 chroot) is having some hardware problems, I'll have to troubleshoot it before I can test again twin on arm32

**Comment by jafcobend** [comment] 2022-09-23 21:11
I'll give it a whirl!

**Comment by jafcobend** [comment] 2022-09-24 04:41
The new code **won't** compile on my machines. The last commit that I have compiled was #e91ef22. It looks like your using newer features of C++ then what I have available. I won't be changing that. I was able to back-port commit #036fb3f onto that and it does solve the 32bit `twterm &` issue. And the close buttons work again with the other clients too. I'll test it on 64bit stuff in the next day or so. Thanks!

**Comment by cosmos72** [comment] 2022-09-24 07:44
Ouch.
If you post the compile errors you get compiling current master branch without modifications, and the compiler version you are using, I'll try to fix it.

I've recently modified twin to require C++11 - even old g++ / clang++ versions should grok it.

**Comment by jafcobend** [comment] 2022-09-24 16:39
This has been fun while it lasted, but this is apparently where our roads diverge. Thank you for that 32bit fix. I'll keep you posted on issue #76. Its been running on several devices for a few days now. Maybe it was that glitchy USB hub that caused the problem, although I hadn't seen any of the other usual symptoms.

IMO its unreasonable, at best, to expect users to upgrade their OS just to run your software. I realize this is the accepted practice of the Open Source community at large. IMO C++11 is the minimum that C++ should be. Its a shame it took so long to come around and even greater shame it took soooo long for GNU to adopt it. But this is the reality we live in. I force myself to write for the older C++ standards to enable more users/devices to be able run my software. You orphaned a **LOT** of devices with these recent changes.

As one of the WINE developers said;

> The only stable API on Linux is WINE (windows) =-O

That's not entirely true. Linus is downright militant about "breaking user space".

That said: only one out of the dozen or so machines I have in my local stable can compile TWIN since some time after commit #e91ef22. And most of my devices do C++11. Nothing in my remote stables will compile it. I'll take this and preserve it as the last version that can be run on nearly everything.

> So long and thanks for the fish

:-)

**Comment by cosmos72** [comment] 2022-09-24 17:44
I have read your post twice, and I still cannot figure out what you mean exactly.

If you post the compile errors you are getting, I'll try to fix them.
If the issue is C++11 being too modern, well, that's something I introduced a only few commits ago for convenience - Consider than twin was 100% pure C (no C++ at all) until ~2 years ago. Reverting to C++98 is slightly inconvenient but feasible.

But then I don't understand what you mean with:
> IMO C++11 is the minimum that C++ should be

**Comment by Mirppc** [comment] 2022-09-24 18:08
> This has been fun while it lasted, but this is apparently where our roads diverge. Thank you for that 32bit fix. I'll keep you posted on issue #76. Its been running on several devices for a few days now. Maybe it was that glitchy USB hub that caused the problem, although I hadn't seen any of the other usual symptoms.
> 
> IMO its unreasonable, at best, to expect users to upgrade their OS just to run your software. I realize this is the accepted practice of the Open Source community at large. IMO C++11 is the minimum that C++ should be. Its a shame it took so long to come around and even greater shame it took soooo long for GNU to adopt it. But this is the reality we live in. I force myself to write for the older C++ standards to enable more users/devices to be able run my software. You orphaned a **LOT** of devices with these recent changes.
> 
> As one of the WINE developers said;
> 
> > The only stable API on Linux is WINE (windows) =-O
> 
> That's not entirely true. Linus is downright militant about "breaking user space".
> 
> That said: only one out of the dozen or so machines I have in my local stable can compile TWIN since some time after commit #e91ef22. And most of my devices do C++11. Nothing in my remote stables will compile it. I'll take this and preserve it as the last version that can be run on nearly everything.
> 
> > So long and thanks for the fish
> 
> :-)

As someone who has worked with older 32bit linux distros for years and continues to... Unless you have an offline reason to use an antiquated 32bit distro, then i would suggest migrating to something else.  I am not saying that you need to throw away your 32bit hardware.  There are distros out there that are still supporting 32bit.

For example i have none of the 32bit issues you ran into on Opensuse Tumbleweed 32bit on a Dell Inspiron 8600.  There is also a 32bit ARCH that is still supported as well as BunsinLabs.  If i remember correctly the latest Tinycore has C++11 support too.

Now with another point i want to make, TWIN is not a huge project and @cosmos72  has been working on TWIN for many many years with many of those being solo.   Fixes and changes take time and effort so having patience would be a great virtue.


So end the end i would call for a little bit of patience, making sure you are running a current and up to date operating system that is being maintained/patched with current software as well as security patches.

**Comment by jafcobend** [comment] 2022-09-24 19:13
@cosmos72, I really need to work on my communication skills. I think I'm an alien. ;-) In short what I was saying is that you are obviously moving toward adopting more modern language features. I've always been moving toward making software available to broader audience, which means supporting the old. These are mutually exclusive directions. And it also goes against everything the Open Source community is currently doing. So I get the fact that I'm the "odd man out".

I won't go into the details about what I meant about C++11. I was just pointing out that although I'd prefer to use it, I don't so that I can support the broader audience.

@Mirppc I won't beat a dead horse. I will say that I'm not "impatient". I'm "sadly resigned". I wanted to get involved. But I obviously don't fit in. I would also point out that _my_ issues were **actual** issues that @cosmos72 has fixed. Except for possibly the long running thing... and that's still under testing here, and may have been fixed by the changes made in response to this issue. If there is anyone who will stumble into the bugs hiding in the dark corners of software, its me. ::sigh::

@cosmos72 I really do appreciate what you've done. I think you have a really good thing here, **especially** for older or graphically challenged hardware. Frankly its replaced `tmux` and `screen` everywhere I ssh into. It just needs a bunch of apps! ;-)

Since G++ is the only compiler I've ever used that can spit out 3,000 lines of error for a missed bit of punctuation I will cut the error short and only include the top of the report from my c++11 enabled compiler (gcc v4.9.2):

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../include -I../../include -g -O2 -std=c++11 -fomit-frame-pointer -fno-strict-aliasing -pipe -Wall -Wshadow -Wno-uninitialized -Wno-unused -Wundef -Wcast-qual -Wcast-align -Wpointer-arith -Wwrite-strings -MT err.lo -MD -MP -MF .deps/err.Tpo -c err.cpp  -fPIC -DPIC -o .libs/err.o
In file included from ../../include/stl/chars.h:12:0,
                 from err.cpp:14:
../../include/stl/view.h: In member function ‘View<T> View<T>::view(size_t, size_t) const’:
../../include/stl/view.h:128:45: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
   View view(size_t start, size_t end) const {
                                             ^
In file included from err.cpp:14:0:
../../include/stl/chars.h: In member function ‘Chars Chars::view(size_t, size_t) const’:
../../include/stl/chars.h:45:46: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
   Chars view(size_t start, size_t end) const {
                                              ^
err.cpp: At global scope:
err.cpp:30:7: error: no matching function for call to ‘Chars::Chars()’
 Chars Errstr;
       ^
err.cpp:30:7: note: candidates are:
In file included from err.cpp:14:0:
../../include/stl/chars.h:18:15: note: template<long unsigned int N> constexpr Chars::Chars(const char (&)[N])
   using Base::Base; // export base class constructors
               ^
../../include/stl/chars.h:18:15: note:   template argument deduction/substitution failed:
err.cpp:30:7: note:   candidate expects 1 argument, 0 provided
 Chars Errstr;
       ^
In file included from err.cpp:14:0:
../../include/stl/chars.h:18:15: note: constexpr Chars::Chars(const char*, size_t)
   using Base::Base; // export base class constructors
               ^
../../include/stl/chars.h:18:15: note:   candidate expects 2 arguments, 0 provided
../../include/stl/chars.h:18:15: note: Chars::Chars(const Span<char>&)
../../include/stl/chars.h:18:15: note:   candidate expects 1 argument, 0 provided
../../include/stl/chars.h:18:15: note: Chars::Chars(const Vector<char>&)
../../include/stl/chars.h:18:15: note:   candidate expects 1 argument, 0 provided
../../include/stl/chars.h:21:13: note: constexpr Chars::Chars(const Base&)
   constexpr Chars(const Base &chars) : Base(chars) {
```
Note the `-std=c++11` to enable that version.

Thanks guys.

**Comment by cosmos72** [comment] 2022-09-24 22:01
Hi @jafcobend,
twin is intended to be usable and useful **especially** on small or older machines, including "non mainstream" ones.

And it's not surprising to have old OS/distributions on such machines - sometimes because it's not worth upgrading them, more often because their run patched kernels to due hardware support, and such patches have never been merged into mainstream Linux.
My arm development box is an OdroidC2. It is currently stuck with a patched kernel 3.14.29 exactly for that reason (GPU support to be exact), and although I have debian12/aarch64 and debian12/armhf chroots, it's starting to show its age.

So I can only agree with you that updating to the "latest and greatest" version of everything is not usually an option on such systems.

I am thinking about how many C++11 features are currently used in the sources, and the answer is two:
- std::unordered_map - it can be replaced (or conditionally replaced) with std::map
- variadic templates - they are used to implement a type-safe alternative to `printf`, and they can be replaced with operator overloading and a little magic with macros

There's also `constexpr` in some places, but it can be trivially replaced with a `CONSTEXPR` macro that expands to nothing on compilers that do not support it (or when -std=c++11 is not specified and is not the default).

**In summary, it's still very early in the transition to C++11, and I can easily revert it to C++98.**

And don't worry, I won't miss C++11: my full-time job involves programming with C++20 (I am sure a certain colleague will soon propose the switch to C++23). C++20 is a much more complex dialect, and definitely an overkill for a small program as twin is.

Even C++11 or C++98 are not really required - as I said, twin was pure C until ~2 years ago, and I switched to C++98 mainly to modernize and simplify it: emulating OOP in C as twin does is not fun after a certain complexity threshold.

About the error you reported: **the significant line is**
```
err.cpp:30:7: error: no matching function for call to ‘Chars::Chars()’
```
**and fixing it should be easy**, as `Chars` **is** supposed to have a default constructor. It means that your g++ 4.9.2 did not fully understand this fragment:
```
class Chars : : public View<char> {
  typedef View<char> Base;
public:
  using Base::Base; // export base class constructors
  // ...
};
```

**Comment by jafcobend** [comment] 2022-09-24 23:30
Good deal! I _assumed_ that there was deliberate intent to upgrade the code base to more modern dialects. If you want to continue to support the older systems I am certainly ready to aid however I can and will report on any issues I run into with my build cluster. I deliberately run some old OSes in there, like Deb7 on ARM, since that is the first version I'm aware that ran on ARM. Usually you get greater lifespan from binaries built against older libs.

And... I think this bug is done. :-)

**Comment by cosmos72** [comment] 2022-09-25 09:10
Good! I'll open another issue to keep track of tge compile error on g++ 4.9.2

**Closed by cosmos72** 2022-09-25 09:10 UTC
Labels: bug
